#!/bin/bash

sed -e 's/float/double/g' \
    -e 's/double.h/float.h/g' \
    -e 's/0.0f/0.0/g' \
    -e 's/1.0f/1.0/g' \
    -e 's/2.0f/2.0/g' \
    -e 's/FLT_EPSILON/DBL_EPSILON/g' \
    -e 's/3u/1u/g' \
    -e 's/sqrtf/sqrt/g' \
    -e 's/fabsf/fabs/g' \
    -e 's/sinf/sin/g' \
    -e 's/cosf/cos/g' \
    -e 's/logf/log/g' \
    -e 's/sgemm/dgemm/g' \
    -e 's/ssyrk/dsyrk/g' \
    -e 's/strmm/dtrmm/g' \
    -e 's/strsm/dtrsm/g' \
    -e 's/cuSgemm/cuDgemm/g' \
    -e 's/cuSsyrk/cuDsyrk/g' \
    -e 's/cuStrmm/cuDtrmm/g' \
    -e 's/cuStrsm/cuDtrsm/g' \
    -e 's/cuMultiGPUSgemm/cuMultiGPUDgemm/g' \
    -e 's/cuMultiGPUSsyrk/cuMultiGPUDsyrk/g' \
    -e 's/cuMultiGPUStrmm/cuMultiGPUDtrmm/g' \
    -e 's/cuMultiGPUStrsm/cuMultiGPUDtrsm/g' \
    -e 's/SGEMM/DGEMM/g' \
    -e 's/SSYRK/DSYRK/g' \
    -e 's/STRMM/DTRMM/g' \
    -e 's/STRSM/DTRSM/g' \
    -e 's/spotf2/dpotf2/g' \
    -e 's/spotrf/dpotrf/g' \
    -e 's/spotri/dpotri/g' \
    -e 's/slauu/dlauu/g' \
    -e 's/strti2/dtrti2/g' \
    -e 's/strtri/dtrtri/g' \
    -e 's/cuSpotf2/cuDpotf2/g' \
    -e 's/cuSpotrf/cuDpotrf/g' \
    -e 's/cuSpotri/cuDpotri/g' \
    -e 's/cuMultiGPUSpotrf/cuMultiGPUDpotrf/g' \
    -e 's/cuMultiGPUSpotri/cuMultiGPUDpotri/g' \
    -e 's/STRTRI/DTRTRI/g' \
    -e 's/SLAUUM/DLAUUM/g' \
    ${1}
